stages:
  - test

playwright_regress:
  stage: test
  timeout: 2h
  tags:
    - docker
  image: mcr.microsoft.com/playwright:v1.58.2-jammy

  variables:
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: "1"
    PLAYWRIGHT_BROWSERS_PATH: "/ms-playwright"

  before_script:
    - node -v
    - npm -v
    - npm ci
    - mkdir -p allure-results
    - mkdir -p test-results
    - mkdir -p playwright-report

  script:
    - echo "Branch=${Branch:-main} Browser=${Browser:-chromium} Grep=${Grep:-@regress}"
    - test -n "$BASE_URL" || (echo "BASE_URL is NOT set" && exit 1)
    - test -n "$USER_LOGIN" || (echo "USER_LOGIN is NOT set" && exit 1)
    - test -n "$USER_PASSWORD" || (echo "USER_PASSWORD is NOT set" && exit 1)
    - npx playwright test -c playwright.config.ts --project="${Browser:-chromium}" --grep "${Grep:-@regress}"

  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - allure-results/
      - playwright-report/
      - test-results/